#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os, sys

_srcdir = '%s/app/' % os.path.dirname(os.path.realpath(__file__))
_filepath = os.path.dirname(sys.argv[0])
sys.path.insert(1, os.path.join(_filepath, _srcdir))

if sys.version_info[0] == 3:
    from PyQt5.QtWidgets import QApplication
    from app.ui.main_window import MainWindow

    from app.ui.icon_rc import *

    __author__ = 'InG_byr'

    if __name__ == '__main__':
        app = QApplication(sys.argv)
        font = app.font()
        font.setPointSize(11)
        app.setFont(font)
        ui = MainWindow()
        ui.main_window.show()
        sys.exit(app.exec_())
else: # Python 2
    from you_get.util import log
    log.e("[fatal] Python 3 is required!")
    log.wtf("try to run this script using 'python3 gui-youget'.")

