#!/bin/bash

TARGET_FILE="you-get/src/you_get/common.py"

function patch() {
    grep 'third party downloader hack end' ${TARGET_FILE} 1>/dev/null 2>&1
    if [ $? -eq 0 ]
    then
        echo "Seems already patched, will exit now~"
        exit
    fi
    IFS=''
    content=""
    while read line
    do
        content+=${line}"\n"
    done<template

    sed -i ':a;N;$!ba;s/\n/xxooxx/g;s/\(def url_save(\)\([^)]*):\)/\1\2\nCONTENT_DATA/g' ${TARGET_FILE}
    sed -i "s@CONTENT_DATA@${content}@g;s@xxooxx@\n@g" ${TARGET_FILE}

    sed -i ':a;N;$!ba;s/\n/xxooxx/g;s/\(def url_save_chunked(\)\([^)]*):\)/\1\2\nCONTENT_DATA/g' ${TARGET_FILE}
    sed -i "s@CONTENT_DATA@${content}@g;s@xxooxx@\n@g" ${TARGET_FILE}
}

function check_directory() {
    if [ ! -f ${TARGET_FILE} ]
    then
        echo "Use this script under you-get root directory"
        exit
    fi
}

if [ $# -eq 1 ]
then
    c=$1
    case $c in
    "init")
    git clone https://github.com/soimort/you-get/        
    ;;
    "update")
    check_directory
    git checkout .
    git pull
    patch
    ;;
    -h|--help)
    echo "Usage: $0 [init/update]. By default, do the patch work."
    ;;
    esac
else
    check_directory
    git checkout .
    patch
fi
